services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - ConnectionStrings__PostgresConnection=Host=localhost;Port=5432;Database=SemWorkASP;Username=postgres;Password=myhome1861
      - Minio__Endpoint=minio:9000
      - Minio__AccessKey=minioadmin
      - Minio__SecretKey=minioadmin
      - Minio__BucketName=semwork
      - Minio__UseSSL=false
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=SemWorkASP
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myhome1861
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d SemWorkASP"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  minio_data: